[workspace]
members = [
    "apps/client",
    "apps/server",
    "crates/configs",
    "crates/design",
    "crates/content",
    "crates/network",
    "crates/simulation",
    "crates/world_data",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"

[workspace.dependencies]
bevy = { version = "=0.19.1", default-features = false }
gilrs = "0.11.2"
lightyear = { version = "=0.28.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"

[profile.dev]
opt-level = 1
debug = 1
incremental = false

[profile.dev.package."*"]
opt-level = 3
debug = 1
