[package]
name = "game01-simulation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = ["std"] }
game01-configs = { path = "../configs" }
game01-design = { path = "../design" }
game01-content = { path = "../content" }
game01-world-data = { path = "../world_data" }
