[package]
name = "game01-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = [
    "std",
    "multi_threaded",
    "bevy_log",
    "bevy_state",
] }
game01-configs = { path = "../../crates/configs" }
game01-content = { path = "../../crates/content" }
game01-network = { path = "../../crates/network", default-features = false, features = ["server"] }
game01-simulation = { path = "../../crates/simulation" }
game01-world-data = { path = "../../crates/world_data" }
