[package]
name = "game01-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
dev = ["bevy/dynamic_linking"]

[dependencies]
bevy = { workspace = true, features = [
    "default_app",
    "std",
    "multi_threaded",
    "bevy_winit",
    "2d_bevy_render",
    "default_font",
    "keyboard",
    "mouse",
    "x11",
    "wayland",
] }
game01-network = { path = "../../crates/network" }
game01-configs = { path = "../../crates/configs" }
game01-world-data = { path = "../../crates/world_data" }
