[package]
name = "game01-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bevy = { workspace = true, features = ["std", "bevy_log"] }
game01-world-data = { path = "../world_data" }
serde.workspace = true
lightyear = { workspace = true, features = [
    "std",
    "client",
    "server",
    "replication",
    "netcode",
    "udp",
] }
